
/**
 * @file {{ image.name }}.h
 * @brief Image "{{ image.name }}" generated from "{{ image.source }}"
 * 
 * Generated by ebs-image version {{ libversion }} using Image Format class
 * {{ classname }} and encoded with {{ image.encoding }}.
 *
 * The estimated size of the generated image is {{ image.packed_size }} bytes.
 *
 * @see {{ image.name }}.c
 */

#include <graphics/image.h>

extern const image_t {{ image.name }};
