
/**
 * @file {{ image.name }}.h
 * @brief Image "{{ image.name }}" generated from "{{ image.source }}"
 * 
 * Generated by ebs-image version {{ libversion }} using Image Format class
 * {{ classname }}
 *
 * @see {{ image.name }}.c
 */

#include "<graphics/image.h>"

extern const image_t {{ image.name }};
